#     _    _ _ ____  _
#    / \  | | / ___|(_) __ _ _ __  ___
#   / _ \ | | \___ \| |/ _` | '_ \/ __|
#  / ___ \| | |___) | | (_| | | | \__ \
# /_/   \_\_|_|____/|_|\__, |_| |_|___/
#                      |___/
# (C) 2021 by surva network | https://github.com/survanetwork

# Language of the plugin messages
# Possible options are: en (English), de (German), ru (Russian), ja (Japanese), vi (Vietnamese)
language: "en"

# Try to automatically detect the player's language and send translated messages for each player
# (language set above is used if player's language can't be detected)
autodetectlanguage: true
